# Fuse Core Theme for Jekyll - Settings
# https://github.com/tsjensen/fuse-core

markdown: kramdown
permalink: pretty
exclude: ['README.*', 'LICENSE.txt']
sass:
    style: expanded


# CAUTION
# When modifying this file, take care to preserve the indentation. This is YAML ...

# Main Headline, name required, subtitle optional
name: Paul F. Jaeger
#subtitle:
subtitle: Postdoc at <a href="https://www.dkfz.de/en/mic/index.php" style="color:rgb(211,211,211)">MIC-DKFZ</a>.
  Previously PhD Candidate at <a href="https://cvhci.anthropomatik.kit.edu/587.php" style="color:rgb(211,211,211)">KIT</a> and Research Intern at <a href="https://research.fb.com/category/facebook-ai-research/index.php" style="color:rgb(211,211,211)">Facebook AI</a>.

# Title attribute of HTML Page, uses 'name' from above if empty
title:

# Information for web crawlers / Google, all of them optional
# 'description' and 'keywords' simply set the corresponding meta tags,
# 'crawl' is the 'Robots' tag http://www.robotstxt.org/meta.html
robots:
    description: Paul F. Jaeger
    keywords: Paul F. Jaeger, Paul Jaeger
    crawl: index,follow

# website address when deployed, also given as canonical link
url: https://pfjaeger.github.io/

# The 'baseurl' is prepended to all website-internal links.
# 'baseurl' will often be '', but for a project page on gh-pages, it needs to be the project name.
# If not empty, be careful to keep the leading slash, and don't add a slash at the end.
#baseurl: ''
baseurl: ''

# Enable Google Analytics. Leave empty (just "ga:" with subitems commented out) to disable.
# In order to comply with EU cookie law, enable 'cookieconsent' to show a little popup asking users to acknowledge the GA cookies.
# Also, some places require you to anonymize the users' IPs, which can be enabled via 'anonymizeip' below. You normally want that.
# https://support.google.com/analytics/answer/2763052
#ga:
ga:
    account: ''
    cookieconsent: true
    anonymizeip: true


# A picture of you, square(!), at least 180x180 pixels, more is better. Recommended file size < 100 KB.
# Leave empty for generic placeholder image.
# You can use your GitHub image:
avatar: "images/paul_new_foto_squared_lowres.jpg"
#avatar: "images/jonathan_doe.jpg"
#avatar:


# All the social media and other sites that we want to link to. The 'show' flag determines if the link is shown.
# The order of this list controls the order of the links on the page. Feel free to add.
links:
  - github:
      name: GitHub
      show: true
      href: https://github.com/pfjaeger
      icon: fab fa-github
  - googlescholar:
      name: Google Scholar
      show: true
      href: https://scholar.google.de/citations?user=9B9-8h0AAAAJ&hl=de
      icon: fas fa-graduation-cap
  - CV:
      name: CV
      show: true
      href: https://drive.google.com/file/d/1NsS-MKQVfvtH04yEVrVb3QaJ8z5xXfCk/view?usp=sharing
      icon: fas fa-file
  - twitter:
      name: Twitter
      show: true
      href: https://twitter.com/pfjaeger
      icon: fab fa-twitter
  - email:
      name: Email
      show: true
      href: mailto:p.jaeger@dkfz.de
      icon: fas fa-envelope
  - hdai:
      name: Heidelberg AI
      show: true
      href: https://heidelberg.ai
      icon: fas fa-users


# Extra HTML which will be displayed below the links. Keep it short. Leave empty to disable.
extra_html:

  <br><br><br><br><br>
  test5
  <div id="presentation-embed-38923239"></div>
  <script src='https://slideslive.com/embed_presentation.js'></script>
  <script>
  embed = new SlidesLiveEmbed('presentation-embed-38923239', {
  presentationId: '38923239',
  autoPlay: false, // change to true to autoplay the embedded presentation
  verticalEnabled: true
  });
  </script>
  <br><br><br><br><br><br><br>

#EOF
#<script src='https://slideslive.com/embed_presentation.js'></script>
#<script>
#embed = new SlidesLiveEmbed('presentation-embed-38923239', {
#presentationId: '38923239',
#autoPlay: false, // change to true to autoplay the embedded presentation
#verticalEnabled: true
#});
#</script>