# Fuse Core Theme for Jekyll - Settings
# https://github.com/tsjensen/fuse-core

markdown: kramdown
permalink: pretty
exclude: ['README.*', 'LICENSE.txt']
sass:
    style: expanded


# CAUTION
# When modifying this file, take care to preserve the indentation. This is YAML ...

# Main Headline, name required, subtitle optional
name: Paul F. Jaeger
#subtitle:
subtitle: Health AI Researcher at Google DeepMind. Ex- DKFZ, ELLIS, KIT, and Meta FAIR</a>.

# Title attribute of HTML Page, uses 'name' from above if empty
title:

# Information for web crawlers / Google, all of them optional
# 'description' and 'keywords' simply set the corresponding meta tags,
# 'crawl' is the 'Robots' tag http://www.robotstxt.org/meta.html
robots:
    description: Paul F. Jaeger
    keywords: Paul F. Jaeger, Paul Jaeger
    crawl: index,follow

# website address when deployed, also given as canonical link
url: https://pfjaeger.github.io/

# The 'baseurl' is prepended to all website-internal links.
# 'baseurl' will often be '', but for a project page on gh-pages, it needs to be the project name.
# If not empty, be careful to keep the leading slash, and don't add a slash at the end.
#baseurl: ''
baseurl: ''

# Enable Google Analytics. Leave empty (just "ga:" with subitems commented out) to disable.
# In order to comply with EU cookie law, enable 'cookieconsent' to show a little popup asking users to acknowledge the GA cookies.
# Also, some places require you to anonymize the users' IPs, which can be enabled via 'anonymizeip' below. You normally want that.
# https://support.google.com/analytics/answer/2763052
#ga:
ga:
    account: ''
    cookieconsent: true
    anonymizeip: true


# A picture of you, square(!), at least 180x180 pixels, more is better. Recommended file size < 100 KB.
# Leave empty for generic placeholder image.
# You can use your GitHub image:
avatar: "images/headshotPaulJaeger7720-lo.jpg"
#avatar:


# All the social media and other sites that we want to link to. The 'show' flag determines if the link is shown.
# The order of this list controls the order of the links on the page. Feel free to add.
links:
  - github:
      name: GitHub
      show: true
      href: https://github.com/pfjaeger
      icon: fab fa-github
  - googlescholar:
      name: Google Scholar
      show: true
      href: https://scholar.google.de/citations?user=9B9-8h0AAAAJ&hl=de
      icon: fas fa-graduation-cap
  - linked:
      name: LinkedIn
      show: true
      href: https://www.linkedin.com/in/paul-f-jaeger-990285122/
      icon: fab fa-linkedin  
  - twitter:
      name: Twitter
      show: true
      href: https://twitter.com/pfjaeger
      icon: fab fa-twitter
  - email:
      name: Email
      show: true
      href: mailto:p.jaeger@dkfz.de
      icon: fas fa-envelope


# Extra HTML which will be displayed below the links. Keep it short. Leave empty to disable.
extra_html: |


 <br><br><br><br><br>
  
  Oral ("top-5% paper") at ICLR 05/2023
  <br><br>
  <a href="https://iclr.cc/virtual/2023/oral/12528" target="_blank">
    <img src="images/iclr_thumbnail.png" alt="Your Image Description" style="width:100%; height:auto;">
  </a>

  <br><br><br><br><br>
  Invited Talk at CAMI Data Science Seminar 11/2020
  <br><br>
  <div id="vid-top">
  <iframe width="100%" height="600" src="https://www.youtube.com/embed/3po8qVzz5Tc" frameborder="0" allow="accelerometer;
  autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>

  <br><br><br><br><br>
  
  Spotlight talk at Neurips (Machine Learning 4 Health Workshop) 12/2019
  <br><br>
  <div id="presentation-embed-38923239"></div>
  <script src='https://slideslive.com/embed_presentation.js'></script>
  <script>
  embed = new SlidesLiveEmbed('presentation-embed-38923239', {
  presentationId: '38923239',
  autoPlay: false,
  verticalEnabled: true,
  demo: false,
  startTime: 568,
  startSlide: 9
   });
   </script>
  
  <br><br><br><br><br>
  
  Invited talk at Encoding Cultures Conference 4/2018
  <br><br>
  <div id="vid-bottom">
  <iframe width="100%" height="600" src="https://www.youtube.com/embed/OHD1CBx6qBI" frameborder="0" allow="accelerometer;
  autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
  <br><br><br><br><br>
  

#<video controlsList="nodownload" oncontextmenu="return false" class="embed-responsive-item" src="https://zkm.de/media/video/i6180_18_MTH_S_VW_BB_EncodingCultures_16_Jaeger_720p.mp4"
 # preload="none" poster='https://zkm.de/media/video/img/i6180_18_mth_s_vh_bb_encodingcultures_jaeger_16.jpg'></video>

#
#  <div class="embed-responsive embed-responsive-16by9">
#              <div class="playpause">
#                <div class="playbutton"></div>
#              </div>
#              <video controlsList="nodownload" oncontextmenu="return false" class="embed-responsive-item" src="https://zkm.de/media/video/i6180_18_MTH_S_VW_BB_EncodingCultures_16_Jaeger_720p.mp4" preload="none" poster='https://zkm.de/media/video/img/i6180_18_mth_s_vh_bb_encodingcultures_jaeger_16.jpg'></video>
#            </div>
#          </div>

#EOF
#<script src='https://slideslive.com/embed_presentation.js'></script>
#<script>
#embed = new SlidesLiveEmbed('presentation-embed-38923239', {
#presentationId: '38923239',
#autoPlay: false, // change to true to autoplay the embedded presentation
#verticalEnabled: true
#});
