# Fuse Core Theme for Jekyll - Settings
# https://github.com/tsjensen/fuse-core

markdown: kramdown
permalink: pretty
exclude: ['README.*', 'LICENSE.txt']
sass:
    style: expanded


# CAUTION
# When modifying this file, take care to preserve the indentation. This is YAML ...

# Main Headline, name required, subtitle optional
name: Paul F. Jaeger
#subtitle:
subtitle: PhD Candidate at KIT and MIC-DKFZ

# Title attribute of HTML Page, uses 'name' from above if empty
title:

# Information for web crawlers / Google, all of them optional
# 'description' and 'keywords' simply set the corresponding meta tags,
# 'crawl' is the 'Robots' tag http://www.robotstxt.org/meta.html
robots:
    description: One line of text describing the content of the page in less than 140 characters.
    keywords: foo, bar, baz
    crawl: index,follow

# website address when deployed, also given as canonical link
url: https://pfjaeger.github.io/

# The 'baseurl' is prepended to all website-internal links.
# 'baseurl' will often be '', but for a project page on gh-pages, it needs to be the project name.
# If not empty, be careful to keep the leading slash, and don't add a slash at the end.
#baseurl: ''
baseurl: ''

# Enable Google Analytics. Leave empty (just "ga:" with subitems commented out) to disable.
# In order to comply with EU cookie law, enable 'cookieconsent' to show a little popup asking users to acknowledge the GA cookies.
# Also, some places require you to anonymize the users' IPs, which can be enabled via 'anonymizeip' below. You normally want that.
# https://support.google.com/analytics/answer/2763052
#ga:
ga:
    account: ''
    cookieconsent: true
    anonymizeip: true


# A picture of you, square(!), at least 180x180 pixels, more is better. Recommended file size < 100 KB.
# Leave empty for generic placeholder image.
# You can use your GitHub image:
avatar: "https://pbs.twimg.com/profile_images/839191751755763713/bl9GpETD_400x400.jpg"
#avatar: "images/jonathan_doe.jpg"
#avatar:


# All the social media and other sites that we want to link to. The 'show' flag determines if the link is shown.
# The order of this list controls the order of the links on the page. Feel free to add.
links:
   - googlescholar:
      name: Google Scholar
      show: true
      href: https://scholar.google.de/citations?user=9B9-8h0AAAAJ&hl=de
      icon: fas fa-graduation-cap
  - github:
      name: GitHub
      show: true
      href: https://github.com/pfjaeger
      icon: fab fa-github
  - email:
      name: Email
      show: true
      href: mailto:p.jaeger@dkfz.de
      icon: fas fa-envelope
  - twitter:
      name: Twitter
      show: true
      href: https://twitter.com/pfjaeger
      icon: fab fa-twitter
  - hdai:
      name: Heidelberg AI
      show: true
      href: https://heidelberg.ai
      icon: fas fa-keynote
  - medium:
      name: Medium
      show: true
      href: https://medium.com/@YOUR_MEDIUM_USERNAME
      icon: fab fa-medium


# Extra HTML which will be displayed below the links. Keep it short. Leave empty to disable.
#extra_html:
extra_html: >
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    

#EOF
